#!/bin/bash
if [ -z "$SPARKOPTS" ] ; then
echo "you must first source init_spark.sh"
exit
fi

#

export PYSPARK_DRIVER_PYTHON=ipython
# try desc v3
#export JAVA_HOME=/usr
if [ -f /opt/anaconda3/etc/profile.d/conda.sh ] ; then
source /opt/anaconda3/etc/profile.d/conda.sh
conda activate base
fi


cmd="pyspark $SPARKOPTS --jars $JARS"
echo $cmd
eval $cmd 
